#!/bin/sh
# RC Script for Tiny Core Linux
# (c) Robert Shingledecker 2004-2012
#  +  afterboot + wait 4 tc + log
#     by Roberto A. Foglietta, 2021

function uptimeshow() {
	echo -e "\e[1;33mUptime: $(cat /proc/uptime | cut -d' ' -f1) s\e[0m"
}

function infotime() {
	tm="$(printf '%5.2f' $(cat /proc/uptime | cut -d' ' -f1))"
	echo -e "\e[1;36m[$tm] $1\e[0m"
}

function devdir() {
	sed -ne "s,^$1 \([^ ]*\) .*,\1,p" /proc/mounts | head -n1
}

function gettcdev() {
	blkid --label $tclabel
}

logfile=/var/log/tcboot.log
tclabel=T1NYC0R3

if [ "$1" != "log" ]; then
	exec 3>&1 4>&2
	$0 log 2>&1 | tee $logfile
	exit $?
fi

# Mount /proc.
[ -f /proc/cmdline ] || /bin/mount /proc

# Wait for hardware be ready
echo -e "\n\e[1;36mWait for $tclabel\e[0m"
for i in $(seq 1 10); do
	if gettcdev; then
		break;
	fi >/dev/null
	sleep 1
done

# Remount rootfs rw.
/bin/mount -o remount,rw /

# Mount system devices from /etc/fstab.
/bin/mount -a

/etc/init.d/tc-config

echo
tcdev=$(gettcdev)
if [ "$tcdev" == "" ]; then
	infotime "Searching for afterboot.sh: NOT FOUND"
else
	ln -sf $tcdev /etc/sysconfig/tcdev
	tcdir=$(devdir $tcdev)
	if [ "$tcdir" == "" ]; then
		tcdir=${tcdev/dev/mnt}
		mkdir -p $tcdir
		chown root.staff $tcdir
		if mount -o ro,gid=50,umask=002 $tcdev $tcdir; then
			if [ -d $tcdir/tce/optional ]; then
				rm -f /etc/sysconfig/tcedir
				ln -sf $tcdir/tce /etc/sysconfig/tcedir
			fi
		else
			mount -o ro $tcdev $tcdir
		fi 2>/dev/null
		if ! grep -qe "^$tcdev $tcdir " /proc/mounts; then
			tcdir=""
		fi
	fi
	if [ "$tcdev" == "/dev/sr0" ]; then
		ln -sf $tcdir/extra /etc/sysconfig/dtdir
	else
		ln -sf ${tcdev%1}2 /etc/sysconfig/dtdev
	fi
	infotime "Searching for afterboot.sh in $tcdev"
	if [ "$tcdir" != "" ]; then
		ln -sf $tcdir /etc/sysconfig/tcdir
		if [ -f $tcdir/afterboot.sh ]; then
			echo
			echo -e "\e[1;37m############# AFTER BOOT SCRIPT START #############\e[0m"
			echo
			$tcdir/afterboot.sh
		fi
	fi
fi

echo
echo "The boot log is available in $logfile"
uptimeshow
echo
echo -e "\e[1;37m############# PRESS ENTER TO CONTINUE #############\e[0m"
echo "Auto login in 5 seconds..."
timeout 5 dd bs=1 count=1
exec 1>&3 2>&4
clear

