#!/bin/ash
#
# $wd/develop-meta
#

echo "$0" >/run/develop-meta.load
exec >>/run/develop-meta.load 2>&1
set -x

wd=$(dirname $0)

time $wd/fuse
time $wd/binutils
time $wd/libtirpc
time $wd/openssl-1.1.1

nohup $wd/ca-certificates >/dev/null 2>&1 &

