#!/bin/ash
#
# $wd/develop-meta
#

echo "$0" >/run/develop-meta.load
exec >>/run/develop-meta.load 2>&1
set -x

wd=$(dirname $0)

time $wd/binutils
time $wd/openssl-1.1.1

if true; then
	$wd/ca-certificates
	touch /run/ca-certificates.done
fi >/dev/null 2>&1 &

